// @generated
// This file is @generated by prost-build.
/// EventCreateConsensusISM defines the event type emitted when creating a generic State Transition Verifier.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventCreateConsensusIsm {
    /// the owner or creator 
    #[prost(string, tag="1")]
    pub owner: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub trusted_state: ::prost::alloc::vec::Vec<u8>,
    /// the sp1 groth16 verifier key (hex-encoded)
    #[prost(string, tag="3")]
    pub groth16_vkey: ::prost::alloc::string::String,
    /// hash-based commitment to the verifier key used for state transition (hex-encoded)
    #[prost(string, tag="4")]
    pub state_transition_vkey: ::prost::alloc::string::String,
}
/// EventUpdateConsensusISM defines the event type emitted when updating a generic State Transition Verifier.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventUpdateConsensusIsm {
    #[prost(bytes="vec", tag="1")]
    pub trusted_state: ::prost::alloc::vec::Vec<u8>,
}
/// EventCreateEvolveEvmISM defines the event type emitted when creating a new EvolveEvmISM.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventCreateEvolveEvmIsm {
    /// unique hyperlane identifier
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// the owner or creator of the ism
    #[prost(string, tag="2")]
    pub owner: ::prost::alloc::string::String,
    /// state commitment root of the remote chain
    #[prost(string, tag="3")]
    pub state_root: ::prost::alloc::string::String,
    /// latest tracked height of the remote chain
    #[prost(uint64, tag="4")]
    pub height: u64,
    /// trusted celestia header hash
    #[prost(string, tag="5")]
    pub celestia_header_hash: ::prost::alloc::string::String,
    /// trusted celestia height
    #[prost(uint64, tag="6")]
    pub celestia_height: u64,
    /// the celestia namespace identifier used by the application (hex-encoded)
    #[prost(string, tag="7")]
    pub namespace: ::prost::alloc::string::String,
    /// the public key of the sequencer (hex-encoded)
    #[prost(string, tag="8")]
    pub sequencer_public_key: ::prost::alloc::string::String,
    /// the sp1 groth16 verifier key (hex-encoded)
    #[prost(string, tag="9")]
    pub groth16_vkey: ::prost::alloc::string::String,
    /// hash-based commitment to the verifier key used for state transition (hex-encoded)
    #[prost(string, tag="10")]
    pub state_transition_vkey: ::prost::alloc::string::String,
    /// hash-based commitment to the verifier key used for state membership (hex-encoded)
    #[prost(string, tag="11")]
    pub state_membership_vkey: ::prost::alloc::string::String,
}
/// EventUpdateEvolveEvmISM defines the event type emitted when updating a EvolveEvmISM.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventUpdateEvolveEvmIsm {
    /// unique hyperlane identifier
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// state commitment root of the remote chain
    #[prost(string, tag="2")]
    pub state_root: ::prost::alloc::string::String,
    /// latest tracked height of the remote chain
    #[prost(uint64, tag="3")]
    pub height: u64,
    /// trusted celestia header hash
    #[prost(string, tag="4")]
    pub celestia_header_hash: ::prost::alloc::string::String,
    /// trusted celestia height
    #[prost(uint64, tag="5")]
    pub celestia_height: u64,
}
/// EventSubmitMessages defines the event type emitted after successful message submission.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventSubmitMessages {
    /// unique hyperlane identifier
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// state commitment root used to verify messages (hex-encoded)
    #[prost(string, tag="2")]
    pub state_root: ::prost::alloc::string::String,
    /// list of authorized messages ids
    #[prost(string, repeated, tag="3")]
    pub messages: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// ConsensusISM defines the generic Consensus verification module.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConsensusIsm {
    /// unique hyperlane identifier
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// the owner or creator 
    #[prost(string, tag="2")]
    pub owner: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="3")]
    pub trusted_state: ::prost::alloc::vec::Vec<u8>,
    /// the sp1 groth16 verifier key (hex-encoded)
    #[prost(bytes="vec", tag="4")]
    pub groth16_vkey: ::prost::alloc::vec::Vec<u8>,
    /// hash-based commitment to the verifier key used for state transition (hex-encoded)
    #[prost(bytes="vec", tag="5")]
    pub state_transition_vkey: ::prost::alloc::vec::Vec<u8>,
}
/// EvolveEvmISM defines the Hyperlane interchain security module (ISM).
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvolveEvmIsm {
    /// unique hyperlane identifier
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// the owner or creator of the ism
    #[prost(string, tag="2")]
    pub owner: ::prost::alloc::string::String,
    /// state commitment root of the remote chain
    #[prost(bytes="vec", tag="3")]
    pub state_root: ::prost::alloc::vec::Vec<u8>,
    /// latest tracked height of the remote chain
    #[prost(uint64, tag="4")]
    pub height: u64,
    /// trusted celestia header hash
    #[prost(bytes="vec", tag="5")]
    pub celestia_header_hash: ::prost::alloc::vec::Vec<u8>,
    /// trusted celestia height
    #[prost(uint64, tag="6")]
    pub celestia_height: u64,
    /// the celestia namespace identifier used by the application
    #[prost(bytes="vec", tag="7")]
    pub namespace: ::prost::alloc::vec::Vec<u8>,
    /// the public key of the sequencer
    #[prost(bytes="vec", tag="8")]
    pub sequencer_public_key: ::prost::alloc::vec::Vec<u8>,
    /// the sp1 groth16 verifier key
    #[prost(bytes="vec", tag="9")]
    pub groth16_vkey: ::prost::alloc::vec::Vec<u8>,
    /// hash-based commitment to the verifier key used for state transition
    #[prost(bytes="vec", tag="10")]
    pub state_transition_vkey: ::prost::alloc::vec::Vec<u8>,
    /// hash-based commitment to the verifier key used for state membership
    #[prost(bytes="vec", tag="11")]
    pub state_membership_vkey: ::prost::alloc::vec::Vec<u8>,
}
/// Params defines the zk ism module parameters.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Params {
    #[prost(uint32, tag="1")]
    pub max_header_hashes: u32,
}
/// GenesisState defines the zkism module's genesis state.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GenesisState {
    /// list of zk execution isms.
    #[prost(message, repeated, tag="1")]
    pub isms: ::prost::alloc::vec::Vec<EvolveEvmIsm>,
    /// TODO: add messages to genesis state
    /// params is the module parameters.
    #[prost(message, optional, tag="2")]
    pub params: ::core::option::Option<Params>,
}
/// QueryIsmRequest is the request type for the Ism rpc method.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryIsmRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
/// QueryIsmResponse is the response type for the Ism rpc method.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryIsmResponse {
    #[prost(oneof="query_ism_response::Ism", tags="1, 2")]
    pub ism: ::core::option::Option<query_ism_response::Ism>,
}
/// Nested message and enum types in `QueryIsmResponse`.
pub mod query_ism_response {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Ism {
        #[prost(message, tag="1")]
        ConsensusIsm(super::ConsensusIsm),
        #[prost(message, tag="2")]
        EvolveEvmIsm(super::EvolveEvmIsm),
    }
}
/// QueryIsmsRequest is the request type for the Isms rpc method.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryIsmsRequest {
    /// pagination defines an optional pagination for the request.
    #[prost(message, optional, tag="1")]
    pub pagination: ::core::option::Option<super::super::super::cosmos::base::query::v1beta1::PageRequest>,
}
/// QueryIsmsResponse is the response type for the Isms rpc method.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryIsmsResponse {
    /// ism_ids is a list of all registered ISM IDs (from both EvolveEvmISM and ConsensusISM).
    #[prost(string, repeated, tag="1")]
    pub ism_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// pagination defines the pagination in the response.
    #[prost(message, optional, tag="2")]
    pub pagination: ::core::option::Option<super::super::super::cosmos::base::query::v1beta1::PageResponse>,
}
/// QueryParamsRequest is the request type for the Params rpc method.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QueryParamsRequest {
}
/// QueryParamsResponse is the response type for the Params rpc method.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QueryParamsResponse {
    /// params contains the module parameters
    #[prost(message, optional, tag="1")]
    pub params: ::core::option::Option<Params>,
}
/// MsgCreateConsensusISM is the request type for CreateConsensusISM
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgCreateConsensusIsm {
    /// creator is the message sender.
    #[prost(string, tag="1")]
    pub creator: ::prost::alloc::string::String,
    /// the initial trusted state that must be used to generate the first proof
    #[prost(bytes="vec", tag="2")]
    pub trusted_state: ::prost::alloc::vec::Vec<u8>,
    /// the sp1 groth16 verifier key
    #[prost(bytes="vec", tag="3")]
    pub groth16_vkey: ::prost::alloc::vec::Vec<u8>,
    /// hash-based commitment to the verifier key used for state transition
    #[prost(bytes="vec", tag="4")]
    pub state_transition_vkey: ::prost::alloc::vec::Vec<u8>,
}
/// MsgCreateConsensusISMResponse is the response type for CreateConsensusISM
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgCreateConsensusIsmResponse {
    #[prost(bytes="vec", tag="1")]
    pub trusted_state: ::prost::alloc::vec::Vec<u8>,
}
/// MsgUpdateConsensusISM is the request type for UpdateEvolveEvmISM.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgUpdateConsensusIsm {
    /// ism identifier
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// proof is the ZK proof bytes (groth16).
    #[prost(bytes="vec", tag="2")]
    pub proof: ::prost::alloc::vec::Vec<u8>,
    /// the public values used for proof verification.
    #[prost(bytes="vec", tag="3")]
    pub public_values: ::prost::alloc::vec::Vec<u8>,
    /// the tx signer address
    #[prost(string, tag="4")]
    pub signer: ::prost::alloc::string::String,
}
/// MsgUpdateConsensusISMResponse is the response type for State Transition Verifier.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgUpdateConsensusIsmResponse {
    #[prost(bytes="vec", tag="1")]
    pub trusted_state: ::prost::alloc::vec::Vec<u8>,
}
/// MsgCreateEvolveEvmISM is the request type for CreateEvolveEvmISM.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgCreateEvolveEvmIsm {
    /// creator is the message sender.
    #[prost(string, tag="1")]
    pub creator: ::prost::alloc::string::String,
    /// state commitment root of the remote chain
    #[prost(bytes="vec", tag="2")]
    pub state_root: ::prost::alloc::vec::Vec<u8>,
    /// latest tracked height of the remote chain
    #[prost(uint64, tag="3")]
    pub height: u64,
    /// trusted celestia header hash
    #[prost(bytes="vec", tag="4")]
    pub celestia_header_hash: ::prost::alloc::vec::Vec<u8>,
    /// trusted celestia height
    #[prost(uint64, tag="5")]
    pub celestia_height: u64,
    /// the celestia namespace identifier used by the application
    #[prost(bytes="vec", tag="6")]
    pub namespace: ::prost::alloc::vec::Vec<u8>,
    /// the public key of the sequencer
    #[prost(bytes="vec", tag="7")]
    pub sequencer_public_key: ::prost::alloc::vec::Vec<u8>,
    /// the sp1 groth16 verifier key
    #[prost(bytes="vec", tag="8")]
    pub groth16_vkey: ::prost::alloc::vec::Vec<u8>,
    /// hash-based commitment to the verifier key used for state transition
    #[prost(bytes="vec", tag="9")]
    pub state_transition_vkey: ::prost::alloc::vec::Vec<u8>,
    /// hash-based commitment to the verifier key used for state membership
    #[prost(bytes="vec", tag="10")]
    pub state_membership_vkey: ::prost::alloc::vec::Vec<u8>,
}
/// MsgCreateEvolveEvmISMResponse is the response type for CreateEvolveEvmISM.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgCreateEvolveEvmIsmResponse {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
/// MsgUpdateEvolveEvmISM is the request type for UpdateEvolveEvmISM.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgUpdateEvolveEvmIsm {
    /// ism identifier
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// proof is the ZK proof bytes (groth16).
    #[prost(bytes="vec", tag="2")]
    pub proof: ::prost::alloc::vec::Vec<u8>,
    /// the public values used for proof verification.
    #[prost(bytes="vec", tag="3")]
    pub public_values: ::prost::alloc::vec::Vec<u8>,
    /// the tx signer address
    #[prost(string, tag="4")]
    pub signer: ::prost::alloc::string::String,
}
/// MsgUpdateEvolveEvmISMResponse is the response type for UpdateEvolveEvmISM.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgUpdateEvolveEvmIsmResponse {
    /// state commitment root of the remote chain
    #[prost(string, tag="1")]
    pub state_root: ::prost::alloc::string::String,
    /// latest tracked height of the remote chain
    #[prost(uint64, tag="2")]
    pub height: u64,
    /// trusted celestia header hash
    #[prost(string, tag="3")]
    pub celestia_header_hash: ::prost::alloc::string::String,
    /// trusted celestia height
    #[prost(uint64, tag="4")]
    pub celestia_height: u64,
}
/// MsgSubmitMessages is the request type for SubmitMessages.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgSubmitMessages {
    /// ism identifier
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// height is the EVM application height associated with the state transition update.
    #[prost(uint64, tag="2")]
    pub height: u64,
    /// proof is the ZK proof bytes (groth16).
    #[prost(bytes="vec", tag="3")]
    pub proof: ::prost::alloc::vec::Vec<u8>,
    /// the public values used for proof verification.
    #[prost(bytes="vec", tag="4")]
    pub public_values: ::prost::alloc::vec::Vec<u8>,
    /// the tx signer address
    #[prost(string, tag="5")]
    pub signer: ::prost::alloc::string::String,
}
/// MsgSubmitMessagesResponse is the response type for SubmitMessages.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgSubmitMessagesResponse {
}
/// MsgUpdateParams is the request type for UpdateParams.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgUpdateParams {
    /// authority is the address that controls the module (defaults to x/gov unless overwritten).
    #[prost(string, tag="1")]
    pub authority: ::prost::alloc::string::String,
    /// params defines the x/zkism parameters to update.
    ///
    /// NOTE: All parameters must be supplied.
    #[prost(message, optional, tag="2")]
    pub params: ::core::option::Option<Params>,
}
/// MsgUpdateParamsResponse defines the response type for UpdateParams.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgUpdateParamsResponse {
}
include!("celestia.zkism.v1.tonic.rs");
// @@protoc_insertion_point(module)