// @generated
// This file is @generated by prost-build.
/// MsgCreateMailbox ...
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgCreateMailbox {
    /// owner is the message sender.
    #[prost(string, tag="1")]
    pub owner: ::prost::alloc::string::String,
    /// local domain
    #[prost(uint32, tag="2")]
    pub local_domain: u32,
    #[prost(string, tag="3")]
    pub default_ism: ::prost::alloc::string::String,
    /// default_hook ...
    #[prost(string, tag="4")]
    pub default_hook: ::prost::alloc::string::String,
    /// required_hook ...
    #[prost(string, tag="5")]
    pub required_hook: ::prost::alloc::string::String,
}
/// MsgCreateMailboxResponse ...
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgCreateMailboxResponse {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
/// MsgSetMailbox ...
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgSetMailbox {
    /// owner is the message sender.
    #[prost(string, tag="1")]
    pub owner: ::prost::alloc::string::String,
    /// mailbox_id
    #[prost(string, tag="2")]
    pub mailbox_id: ::prost::alloc::string::String,
    /// default_ism ...
    #[prost(string, tag="3")]
    pub default_ism: ::prost::alloc::string::String,
    /// default_hook ...
    #[prost(string, tag="4")]
    pub default_hook: ::prost::alloc::string::String,
    /// required_hook ...
    #[prost(string, tag="5")]
    pub required_hook: ::prost::alloc::string::String,
    /// new_owner ...
    #[prost(string, tag="6")]
    pub new_owner: ::prost::alloc::string::String,
    /// renounce_ownership
    #[prost(bool, tag="7")]
    pub renounce_ownership: bool,
}
/// MsgSetMailboxResponse ...
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgSetMailboxResponse {
}
/// MsgProcessMessage ...
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgProcessMessage {
    /// mailbox_id ...
    #[prost(string, tag="1")]
    pub mailbox_id: ::prost::alloc::string::String,
    /// relayer ...
    #[prost(string, tag="2")]
    pub relayer: ::prost::alloc::string::String,
    /// metadata ...
    #[prost(string, tag="3")]
    pub metadata: ::prost::alloc::string::String,
    /// message ...
    #[prost(string, tag="4")]
    pub message: ::prost::alloc::string::String,
}
/// MsgProcessMessageResponse ...
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgProcessMessageResponse {
}
include!("hyperlane.core.v1.tonic.rs");
// @@protoc_insertion_point(module)